apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: clone-dind-run-
spec:
  pipelineRef:
    name: dind-pipeline
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
