apiVersion: tekton.dev/v1 # or tekton.dev/v1beta1
kind: Task
metadata:
  name: dind
  namespace: default
spec:
  steps:
    - image: docker/compose
      name: client
      script: |
        #!/usr/bin/env sh
        cd /workspace/source
        docker-compose up -d
        sleep 20
      volumeMounts:
        - mountPath: /var/run/
          name: dind-socket
  workspaces:
    - name: source
  sidecars:
    - image: docker:18.05-dind
      name: server
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/lib/docker
          name: dind-storage
        - mountPath: /var/run/
          name: dind-socket
  volumes:
    - name: dind-storage
      emptyDir: {}
    - name: dind-socket
      emptyDir: {}
